spring:
  application:
    name: desafio-itau-vaga-99-junior

springdoc:
  swagger-ui:
    path: /swagger
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: always